/*
 * switch_font.h — embedded PROPORTIONAL 16px-tall 1bpp bitmap font
 * (ASCII + Cyrillic). Generated by scripts/switch_font_gen.py.
 */
#ifndef SWITCH_FONT_H
#define SWITCH_FONT_H

#include <stdint.h>

/* Draw an UTF-8 string into a 32-bit ARGB canvas (MSB in memory: 0xAARRGGBB
 * packed into uint32_t little-endian = BGRA byte order; matches SDL
 * PIXELFORMAT_ARGB8888). bg==0 means transparent. Returns the x after the
 * last glyph (per-glyph PROPORTIONAL advances). Clipped to the canvas. */
int switch_font_draw_text(uint32_t* dst, int dst_w, int dst_h,
                          int x, int y, const char* utf8,
                          uint32_t fg, uint32_t bg, int scale);

/* Width of an UTF-8 string in pixels at the given integer scale
 * (sum of per-glyph advances — pairs with draw_text exactly). */
int switch_font_text_width(const char* utf8, int scale);

/* Legacy metrics. h() = glyph height (16). w() = a fixed-cell hint only —
 * there is NO fixed cell since v36.04; layout code must use
 * switch_font_text_width(). */
int switch_font_w(void);
int switch_font_h(void);

#endif /* SWITCH_FONT_H */
